apiVersion: cluster-scans.ansh.spectro/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: projects
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
spec:
  # TODO(user): Add fields here
